# Generated by Django 5.2.8 on 2025-11-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(help_text='Enter Book Title', max_length=100)),
                ('publication_date', models.DateField()),
                ('isbn_number', models.IntegerField(help_text='Enter the ISBN Number')),
                ('author_name', models.CharField(help_text='Enter Author Name', max_length=50)),
            ],
        ),
    ]
